

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "json_lib",
    remote = "https://github.com/nlohmann/json.git",
    commit = "a3e6e26dc83a726b292f5be0492fcc408663ce55",
)




